import type { Metadata } from "next";
import { Geist, Geist_Mono, Gowun_Batang, Shippori_Mincho } from "next/font/google";
import { LocaleProvider } from "@/components/LocaleProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 엽서 메시지용 손편지 느낌 서체 (한국어/일본어 짝을 맞춤)
// 이 두 폰트는 구글 폰트 쪽에서 언어별로 파일이 나뉘어 있지 않아서
// subsets는 "latin"이지만, 실제 파일 안에 한글/가나·한자 글리프가 전부 들어있음
const gowunBatang = Gowun_Batang({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-message-ko",
});

const shipporiMincho = Shippori_Mincho({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-message-ja",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${gowunBatang.variable} ${shipporiMincho.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LocaleProvider>{children}</LocaleProvider>
      </body>
    </html>
  );
}
